# web port
server:
  port: ${SERVER_PORT:8081}

# log config
logging:
  config: classpath:logback.xml
  path: ${DATA_PATH:.}/applogs/executor/jobhandler

datax:
  job:
    admin:
      ### datax admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://${DATAX_ADMIN_HOST:127.0.0.1}:${DATAX_ADMIN_PORT:9527}
    executor:
      appname: datax-executor
      ip:
      port: ${EXECUTOR_PORT:9999}
      ### job log path
      logpath: ${DATA_PATH:.}/applogs/executor/jobhandler
      ### job log retention days
      logretentiondays: 30
    ### job, access token
    accessToken:

  executor:
    jsonpath: ${JSON_PATH:.}
    pythonpath: python

  pypath: ${PYTHON_PATH:.}