# web port
server:
#  port: ${server.port}
  port: 8081

# log config
logging:
  config: classpath:logback.xml
#  path: ${data.path}/applogs/executor/jobhandler
  path: ./data/applogs/executor/jobhandler

### datax admin address list, such as "http://address" or "http://address01,http://address02"
datax:
  job:
    admin:
      ### datax-web admin address
      addresses: http://127.0.0.1:8080
#      addresses: http://127.0.0.1:${datax.admin.port}
    executor:
      appname: datax-executor
      ip: 127.0.0.1
      port: 9999
#     port: ${executor.port:9999}
      ### job log path
      logpath: ./data/applogs/executor/jobhandler
#      logpath: ${data.path}/applogs/executor/jobhandler
      ### job log retention days
      logretentiondays: 30
    ### job, access token
    accessToken:

  executor:
    jsonpath: /home/hadoop/app/dataxweb/json
#    jsonpath: ${json.path}

  pypath: /home/hadoop/install/datax/bin/datax.py
#  pypath: ${python.path}