# log config
logging:
  path: /data/logs/executor

### datax admin address list, such as "http://address" or "http://address01,http://address02"
datax:
  job:
    admin:
      ### datax-web admin address
      addresses: http://10.6.176.119:8080
    executor:
      appname: datax-executor
      ip:
      port: 9999
      ### job log path
      logpath: /data/logs/executor
      ### job log retention days
      logretentiondays: 30
    ### job, access token
    accessToken: A3Ecl05MWqBD1F

  executor:
    jsonpath: /data/app/datax-job/

  pypath: /data/app/datax/bin/datax.py